version: '3'

networks:
  srm:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv4: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16

volumes:
  mysql:
    driver: local
  srm_mongodb:
    driver: local

services:

  estoque-service:
    image: srm/estoque-service:parte3
    container_name: srm_estoque
    networks:
      srm:
        ipv4_address: 172.32.0.101
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://config-server:8080"
      PROFILE: "default"
  
  pedido-service:
    image: srm/pedido-service:parte3
    container_name: srm_pedido
    networks:
      srm:
        ipv4_address: 172.32.0.106
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://config-server:8080"
      PROFILE: "default"

  config-server:
    image: srm/config-server:parte3
    container_name: srm_configserver
    networks:
      srm:
        ipv4_address: 172.32.0.103
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
    volumes:
      - mysql:/var/lib/mysql
      - ./src/config:/usr/local/config-repo

  database:
    image: mysql:5.7
    container_name: srm_mysql
    command: --init-file /usr/home/database/init.sql
    restart: always
    networks:
      srm:
        ipv4_address: 172.32.0.102
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_srm
      TZ: "America/Sao_Paulo"
    volumes:
      - mysql:/var/lib/mysql
      - ./src/mysql:/usr/home/database

  rabbitmq-srm:
    image: rabbitmq:3-management
    container_name: rabbitmq_srm
    networks:
      srm:
        ipv4_address: 172.32.0.104
  
  service-discovery:
    image: srm/service-discovery:parte3
    container_name: srm_servicediscovery
    networks:
      srm:
        ipv4_address: 172.32.0.105
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
    
  mongodb:
    image: mongo:3.6.3
    container_name: srm_mongo
    command: --bind_ip_all
    networks:
      srm:
        ipv4_address: 172.32.0.107
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: db_srm
    volumes:
      - ./src/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - srm_mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      srm:
        ipv4_address: 172.32.0.108
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
